"""Danh sách ngôn ngữ cho giao diện và thuyết minh — nguồn DUY NHẤT, frontend
đọc qua ``GET /api/v1/languages`` thay vì giữ một bản sao riêng.

Mã là thẻ BCP-47 (``vi``, ``zh-CN``, ``pt-BR``...) để dùng thẳng được cho
``<html lang>`` và ``SpeechSynthesisUtterance.lang`` phía trình duyệt. Tên
tiếng Anh đưa vào prompt cho LLM (model hiểu "French" chắc hơn "fr"); tên bản
ngữ hiển thị trong ô chọn, để người không đọc được tiếng Việt vẫn tìm ra ngôn
ngữ của mình.

Dịch bằng Qwen chạy local (xem ``app/translate.py``): các ngôn ngữ lớn dịch
tốt, ngôn ngữ ít tài nguyên thì kém hơn hẳn — đo được thật 2026-09-25 (tiếng
Swahili dịch sai nghĩa vài nhãn ngắn).
"""

from __future__ import annotations

# (mã, tên tiếng Anh, tên bản ngữ)
LANGUAGES: tuple[tuple[str, str, str], ...] = (
    ("vi", "Vietnamese", "Tiếng Việt"),
    ("en", "English", "English"),
    ("af", "Afrikaans", "Afrikaans"),
    ("sq", "Albanian", "Shqip"),
    ("am", "Amharic", "አማርኛ"),
    ("ar", "Arabic", "العربية"),
    ("hy", "Armenian", "Հայերեն"),
    ("as", "Assamese", "অসমীয়া"),
    ("ay", "Aymara", "Aymar aru"),
    ("az", "Azerbaijani", "Azərbaycanca"),
    ("bm", "Bambara", "Bamanankan"),
    ("eu", "Basque", "Euskara"),
    ("be", "Belarusian", "Беларуская"),
    ("bn", "Bengali", "বাংলা"),
    ("bho", "Bhojpuri", "भोजपुरी"),
    ("bs", "Bosnian", "Bosanski"),
    ("bg", "Bulgarian", "Български"),
    ("ca", "Catalan", "Català"),
    ("ceb", "Cebuano", "Cebuano"),
    ("ny", "Chichewa", "Chichewa"),
    ("zh-CN", "Chinese (Simplified)", "简体中文"),
    ("zh-TW", "Chinese (Traditional)", "繁體中文"),
    ("co", "Corsican", "Corsu"),
    ("hr", "Croatian", "Hrvatski"),
    ("cs", "Czech", "Čeština"),
    ("da", "Danish", "Dansk"),
    ("dv", "Dhivehi", "ދިވެހި"),
    ("doi", "Dogri", "डोगरी"),
    ("nl", "Dutch", "Nederlands"),
    ("eo", "Esperanto", "Esperanto"),
    ("et", "Estonian", "Eesti"),
    ("ee", "Ewe", "Eʋegbe"),
    ("fil", "Filipino", "Filipino"),
    ("fi", "Finnish", "Suomi"),
    ("fr", "French", "Français"),
    ("fy", "Frisian", "Frysk"),
    ("gl", "Galician", "Galego"),
    ("ka", "Georgian", "ქართული"),
    ("de", "German", "Deutsch"),
    ("el", "Greek", "Ελληνικά"),
    ("gn", "Guarani", "Avañe'ẽ"),
    ("gu", "Gujarati", "ગુજરાતી"),
    ("ht", "Haitian Creole", "Kreyòl ayisyen"),
    ("ha", "Hausa", "Hausa"),
    ("haw", "Hawaiian", "ʻŌlelo Hawaiʻi"),
    ("he", "Hebrew", "עברית"),
    ("hi", "Hindi", "हिन्दी"),
    ("hmn", "Hmong", "Hmoob"),
    ("hu", "Hungarian", "Magyar"),
    ("is", "Icelandic", "Íslenska"),
    ("ig", "Igbo", "Igbo"),
    ("ilo", "Ilocano", "Ilokano"),
    ("id", "Indonesian", "Bahasa Indonesia"),
    ("ga", "Irish", "Gaeilge"),
    ("it", "Italian", "Italiano"),
    ("ja", "Japanese", "日本語"),
    ("jv", "Javanese", "Basa Jawa"),
    ("kn", "Kannada", "ಕನ್ನಡ"),
    ("kk", "Kazakh", "Қазақ тілі"),
    ("km", "Khmer", "ភាសាខ្មែរ"),
    ("rw", "Kinyarwanda", "Kinyarwanda"),
    ("gom", "Konkani", "कोंकणी"),
    ("ko", "Korean", "한국어"),
    ("kri", "Krio", "Krio"),
    ("ku", "Kurdish (Kurmanji)", "Kurdî"),
    ("ckb", "Kurdish (Sorani)", "کوردی"),
    ("ky", "Kyrgyz", "Кыргызча"),
    ("lo", "Lao", "ລາວ"),
    ("la", "Latin", "Latina"),
    ("lv", "Latvian", "Latviešu"),
    ("ln", "Lingala", "Lingála"),
    ("lt", "Lithuanian", "Lietuvių"),
    ("lg", "Luganda", "Luganda"),
    ("lb", "Luxembourgish", "Lëtzebuergesch"),
    ("mk", "Macedonian", "Македонски"),
    ("mai", "Maithili", "मैथिली"),
    ("mg", "Malagasy", "Malagasy"),
    ("ms", "Malay", "Bahasa Melayu"),
    ("ml", "Malayalam", "മലയാളം"),
    ("mt", "Maltese", "Malti"),
    ("mi", "Maori", "Te Reo Māori"),
    ("mr", "Marathi", "मराठी"),
    ("mni", "Meiteilon (Manipuri)", "ꯃꯤꯇꯩꯂꯣꯟ"),
    ("lus", "Mizo", "Mizo ṭawng"),
    ("mn", "Mongolian", "Монгол"),
    ("my", "Myanmar (Burmese)", "မြန်မာ"),
    ("ne", "Nepali", "नेपाली"),
    ("no", "Norwegian", "Norsk"),
    ("or", "Odia (Oriya)", "ଓଡ଼ିଆ"),
    ("om", "Oromo", "Afaan Oromoo"),
    ("ps", "Pashto", "پښتو"),
    ("fa", "Persian", "فارسی"),
    ("pl", "Polish", "Polski"),
    ("pt-BR", "Portuguese (Brazil)", "Português (Brasil)"),
    ("pt-PT", "Portuguese (Portugal)", "Português (Portugal)"),
    ("pa", "Punjabi", "ਪੰਜਾਬੀ"),
    ("qu", "Quechua", "Runa Simi"),
    ("ro", "Romanian", "Română"),
    ("ru", "Russian", "Русский"),
    ("sm", "Samoan", "Gagana Sāmoa"),
    ("sa", "Sanskrit", "संस्कृतम्"),
    ("gd", "Scots Gaelic", "Gàidhlig"),
    ("nso", "Sepedi", "Sesotho sa Leboa"),
    ("sr", "Serbian", "Српски"),
    ("st", "Sesotho", "Sesotho"),
    ("sn", "Shona", "chiShona"),
    ("sd", "Sindhi", "سنڌي"),
    ("si", "Sinhala", "සිංහල"),
    ("sk", "Slovak", "Slovenčina"),
    ("sl", "Slovenian", "Slovenščina"),
    ("so", "Somali", "Soomaali"),
    ("es", "Spanish", "Español"),
    ("su", "Sundanese", "Basa Sunda"),
    ("sw", "Swahili", "Kiswahili"),
    ("sv", "Swedish", "Svenska"),
    ("tg", "Tajik", "Тоҷикӣ"),
    ("ta", "Tamil", "தமிழ்"),
    ("tt", "Tatar", "Татарча"),
    ("te", "Telugu", "తెలుగు"),
    ("th", "Thai", "ไทย"),
    ("ti", "Tigrinya", "ትግርኛ"),
    ("ts", "Tsonga", "Xitsonga"),
    ("tr", "Turkish", "Türkçe"),
    ("tk", "Turkmen", "Türkmençe"),
    ("ak", "Twi", "Twi"),
    ("uk", "Ukrainian", "Українська"),
    ("ur", "Urdu", "اردو"),
    ("ug", "Uyghur", "ئۇيغۇرچە"),
    ("uz", "Uzbek", "Oʻzbekcha"),
    ("cy", "Welsh", "Cymraeg"),
    ("xh", "Xhosa", "isiXhosa"),
    ("yi", "Yiddish", "ייִדיש"),
    ("yo", "Yoruba", "Yorùbá"),
    ("zu", "Zulu", "isiZulu"),
)

LANGUAGE_CODES: tuple[str, ...] = tuple(code for code, _, _ in LANGUAGES)
ENGLISH_NAMES: dict[str, str] = {code: english for code, english, _ in LANGUAGES}
SOURCE_LANGUAGE = "vi"


def as_dicts() -> list[dict[str, str]]:
    return [{"code": code, "name": english, "nativeName": native} for code, english, native in LANGUAGES]
