"""POI Knowledge: thêm 30 địa danh (bảo tàng, nhà thờ, chùa, hội quán, chợ, công viên…) cho Săn địa danh, tour và thuyết minh.

Revision ID: 0028_poi_knowledge_landmarks
Revises: 0027_explore_discoveries

Trước migration này chỉ có 16 POI có `poi_knowledge` (12 địa danh săn được) trên
~24.900 POI, nên tour thuyết minh, Săn địa danh và thuyết minh AI đều quanh quẩn
vài địa điểm. Bản này thêm 30 địa danh nữa theo ĐÚNG quy ước của 0022:

- Mọi item (`historical_events` / `interesting_facts`) có `source` (URL) và
  `verified = true`. Nội dung được tra qua WebSearch/WebFetch (chủ yếu Wikipedia
  tiếng Việt, thêm Wikipedia tiếng Anh, Sài Gòn Giải Phóng, Znews, Báo Văn hóa,
  VOV, RFA) ngày 2026-10-03.
- Claim không tìm được nguồn, hoặc các nguồn nói lệch nhau (năm xây, số hiện vật,
  số người…), bị BỎ thay vì giữ lại. Các nội dung nhạy cảm không cần thiết cho
  phần giới thiệu cũng bị bỏ.
- Các bản tóm tắt WebFetch do mô hình nhỏ sinh ra, chưa phải văn bản gốc: số
  liệu cụ thể (ngày, diện tích, số chuông…) nên được đối chiếu lại trước khi dùng
  làm số liệu chính trong báo cáo.

POI được gắn bằng tên chuẩn hoá (pg_trgm) + category + vị trí trong bán kính
300 m — KHÔNG dùng UUID cứng, vì UUID của POI nhập từ OSM đổi sau mỗi lần nhập
lại (xem 0025). POI không tìm thấy thì bỏ qua và ghi log, không làm hỏng
migration. `ON CONFLICT DO NOTHING`: không ghi đè kiến thức đã có.
"""

from __future__ import annotations

import json
import logging
import re
import unicodedata

import sqlalchemy as sa
from alembic import op

revision = "0028_poi_knowledge_landmarks"
down_revision = "0027_explore_discoveries"
branch_labels = None
depends_on = None

logger = logging.getLogger("alembic.runtime.migration")

_RADIUS_M = 300
_MIN_SIMILARITY = 0.6

# (tên POI, category chấp nhận, lat, lon, content_type, intro, intro_source,
#  specialty, historical_context, context_source, historical_events, interesting_facts)
ROWS =[('Bảo tàng Mỹ thuật Thành phố Hồ Chí Minh',
  ('museum',),
  10.7696,
  106.6992,
  'architectural',
  'Bảo tàng đặt trong ngôi nhà ba tầng của thương gia Hui Bon Hoa tại số 97 Phó Đức Chính, trưng bày hội họa, điêu khắc và cổ vật có giá '
  'trị mỹ thuật.',
  'https://vi.wikipedia.org/wiki/B%E1%BA%A3o_t%C3%A0ng_M%E1%BB%B9_thu%E1%BA%ADt_Th%C3%A0nh_ph%E1%BB%91_H%E1%BB%93_Ch%C3%AD_Minh',
  None,
  'Ngôi nhà do kiến trúc sư người Pháp Rivera thiết kế năm 1929 và hoàn thành năm 1934, kết hợp phong cách Á Đông và châu Âu.',
  'https://vi.wikipedia.org/wiki/B%E1%BA%A3o_t%C3%A0ng_M%E1%BB%B9_thu%E1%BA%ADt_Th%C3%A0nh_ph%E1%BB%91_H%E1%BB%93_Ch%C3%AD_Minh',
  [{'title': 'Thiết kế và xây dựng (1929–1934)',
    'description': 'Ngôi nhà được thiết kế năm 1929 và xây xong năm 1934, chủ nhà là thương nhân giàu có Hui Bon Hoa (Huỳnh Văn Hoà).',
    'source': 'https://vi.wikipedia.org/wiki/B%E1%BA%A3o_t%C3%A0ng_M%E1%BB%B9_thu%E1%BA%ADt_Th%C3%A0nh_ph%E1%BB%91_H%E1%BB%93_Ch%C3%AD_Minh',
    'verified': True},
   {'title': 'Lập bảo tàng (1987) và mở cửa (1992)',
    'description': 'Năm 1987 tòa nhà được lập thành Bảo tàng Mỹ thuật TP.HCM, nhưng do thiếu hiện vật nên đến năm 1992 mới đi vào hoạt '
                   'động.',
    'source': 'https://vi.wikipedia.org/wiki/B%E1%BA%A3o_t%C3%A0ng_M%E1%BB%B9_thu%E1%BA%ADt_Th%C3%A0nh_ph%E1%BB%91_H%E1%BB%93_Ch%C3%AD_Minh',
    'verified': True}],
  [{'title': 'Tranh sơn mài của Nguyễn Gia Trí',
    'description': 'Bảo tàng có bức sơn mài "Vườn xuân Bắc Trung Nam" của họa sĩ Nguyễn Gia Trí trong số các tác phẩm tiêu biểu.',
    'source': 'https://vi.wikipedia.org/wiki/B%E1%BA%A3o_t%C3%A0ng_M%E1%BB%B9_thu%E1%BA%ADt_Th%C3%A0nh_ph%E1%BB%91_H%E1%BB%93_Ch%C3%AD_Minh',
    'verified': True},
   {'title': 'Cổ vật Champa và Óc Eo',
    'description': 'Tầng ba trưng bày một số cổ vật Champa và Óc Eo thuộc hàng tốt nhất cả nước.',
    'source': 'https://en.wikipedia.org/wiki/Ho_Chi_Minh_City_Museum_of_Fine_Arts',
    'verified': True}]),
 ('Bảo tàng Lịch sử Thành phố Hồ Chí Minh',
  ('museum',),
  10.788,
  106.7049,
  'historical',
  'Bảo tàng nằm trong khuôn viên Thảo Cầm Viên Sài Gòn (số 2 Nguyễn Bỉnh Khiêm), lưu giữ và trưng bày hàng chục nghìn hiện vật trong và '
  'ngoài nước.',
  'https://vi.wikipedia.org/wiki/B%E1%BA%A3o_t%C3%A0ng_L%E1%BB%8Bch_s%E1%BB%AD_Th%C3%A0nh_ph%E1%BB%91_H%E1%BB%93_Ch%C3%AD_Minh',
  None,
  'Tòa nhà khởi xây năm 1927, khánh thành ngày 1/1/1929 theo thiết kế của kiến trúc sư Auguste Delaval, mang phong cách kiến trúc Đông '
  'Dương cách tân; tên ban đầu là Bảo tàng Blanchard de la Brosse.',
  'https://www.sggp.org.vn/kien-truc-dong-duong-tu-bao-tang-dau-tien-o-phia-nam-post690538.html',
  [{'title': 'Quyết định thành lập (28/11/1927)',
    'description': 'Bảo tàng được thành lập theo nghị định của Thống đốc Nam Kỳ ngày 28/11/1927; tòa nhà khánh thành chính thức ngày '
                   '1/1/1929.',
    'source': 'https://vi.wikipedia.org/wiki/B%E1%BA%A3o_t%C3%A0ng_L%E1%BB%8Bch_s%E1%BB%AD_Th%C3%A0nh_ph%E1%BB%91_H%E1%BB%93_Ch%C3%AD_Minh',
    'verified': True},
   {'title': 'Các lần đổi tên (1956, 1979)',
    'description': 'Năm 1956 bảo tàng mang tên Viện Bảo tàng quốc gia Việt Nam, đến năm 1979 đổi thành Bảo tàng Lịch sử TP.HCM.',
    'source': 'https://www.sggp.org.vn/kien-truc-dong-duong-tu-bao-tang-dau-tien-o-phia-nam-post690538.html',
    'verified': True},
   {'title': 'Mở rộng phần phía sau (1970)',
    'description': 'Năm 1970 phần phía sau được xây thêm theo thiết kế của kiến trúc sư Nguyễn Bá Lăng.',
    'source': 'https://www.sggp.org.vn/kien-truc-dong-duong-tu-bao-tang-dau-tien-o-phia-nam-post690538.html',
    'verified': True}],
  [{'title': 'Khối tháp bát giác',
    'description': 'Mặt bằng công trình có khối tháp bát giác ở giữa làm điểm nhấn; đỉnh mái trang trí hình trái hồ lô, chi tiết console '
                   'cách điệu từ phong cách Huế cổ truyền.',
    'source': 'https://www.sggp.org.vn/kien-truc-dong-duong-tu-bao-tang-dau-tien-o-phia-nam-post690538.html',
    'verified': True},
   {'title': 'Cọc gỗ Bạch Đằng',
    'description': 'Trong số hiện vật trưng bày có cọc gỗ Bạch Đằng từ thế kỷ 13.',
    'source': 'https://vi.wikipedia.org/wiki/B%E1%BA%A3o_t%C3%A0ng_L%E1%BB%8Bch_s%E1%BB%AD_Th%C3%A0nh_ph%E1%BB%91_H%E1%BB%93_Ch%C3%AD_Minh',
    'verified': True}]),
 ('Bảo tàng Phụ nữ Nam Bộ',
  ('museum',),
  10.7842,
  106.6874,
  'cultural',
  'Bảo tàng tại số 202 Võ Thị Sáu giới thiệu vai trò và đóng góp của phụ nữ Nam Bộ qua hơn 31.000 hiện vật, tư liệu.',
  'https://vi.wikipedia.org/wiki/B%E1%BA%A3o_t%C3%A0ng_Ph%E1%BB%A5_n%E1%BB%AF_Nam_B%E1%BB%99',
  None,
  'Bảo tàng có nguồn gốc từ Nhà truyền thống Phụ nữ Nam Bộ, thành lập ngày 29/4/1985 nhân kỷ niệm 10 năm miền Nam giải phóng.',
  'https://vi.wikipedia.org/wiki/B%E1%BA%A3o_t%C3%A0ng_Ph%E1%BB%A5_n%E1%BB%AF_Nam_B%E1%BB%99',
  [{'title': 'Thành lập (29/4/1985)',
    'description': 'Nhà truyền thống Phụ nữ Nam Bộ, tiền thân của bảo tàng, được thành lập ngày 29/4/1985, do bà Nguyễn Thị Thập, nguyên '
                   'Phó Chủ tịch Quốc hội, dẫn dắt tổ nghiên cứu sử phụ nữ Nam Bộ.',
    'source': 'https://vi.wikipedia.org/wiki/B%E1%BA%A3o_t%C3%A0ng_Ph%E1%BB%A5_n%E1%BB%AF_Nam_B%E1%BB%99',
    'verified': True},
   {'title': 'Bảo tàng hạng I (2024)',
    'description': 'Năm 2024 bảo tàng được Bộ Văn hóa, Thể thao và Du lịch công nhận là bảo tàng hạng I.',
    'source': 'https://en.wikipedia.org/wiki/Southern_Women%27s_Museum',
    'verified': True}],
  [{'title': 'Bộ sưu tập áo dài',
    'description': 'Bảo tàng lưu giữ khoảng 200 chiếc áo dài của nhiều phụ nữ tiêu biểu, trong đó có áo của bà Nguyễn Thị Bình, người tham '
                   'gia ký Hiệp định Paris.',
    'source': 'https://vi.wikipedia.org/wiki/B%E1%BA%A3o_t%C3%A0ng_Ph%E1%BB%A5_n%E1%BB%AF_Nam_B%E1%BB%99',
    'verified': True},
   {'title': 'Quy mô hiện vật và thư viện',
    'description': 'Tổng cộng có 31.360 hiện vật, tư liệu (929 đang trưng bày) cùng thư viện hơn 11.000 cuốn sách chuyên đề về phụ nữ.',
    'source': 'https://vi.wikipedia.org/wiki/B%E1%BA%A3o_t%C3%A0ng_Ph%E1%BB%A5_n%E1%BB%AF_Nam_B%E1%BB%99',
    'verified': True}]),
 ('Bảo tàng Tôn Đức Thắng',
  ('museum',),
  10.7774,
  106.7064,
  'historical',
  'Bảo tàng tại số 5 đường Tôn Đức Thắng, Quận 1, giới thiệu cuộc đời và sự nghiệp của Chủ tịch Tôn Đức Thắng.',
  'https://vi.wikipedia.org/wiki/B%E1%BA%A3o_t%C3%A0ng_T%C3%B4n_%C4%90%E1%BB%A9c_Th%E1%BA%AFng',
  None,
  'Bảo tàng thành lập năm 1988; công trình vốn là tư dinh của Trần Thiện Khiêm, Thủ tướng chính quyền Việt Nam Cộng hòa, sau được cải tạo '
  'thành nơi trưng bày.',
  'https://vi.wikipedia.org/wiki/B%E1%BA%A3o_t%C3%A0ng_T%C3%B4n_%C4%90%E1%BB%A9c_Th%E1%BA%AFng',
  [],
  [{'title': 'Năm phòng trưng bày thường trực',
    'description': 'Bảo tàng có 5 phòng trưng bày thường trực, diện tích trên 700 m².',
    'source': 'https://vi.wikipedia.org/wiki/B%E1%BA%A3o_t%C3%A0ng_T%C3%B4n_%C4%90%E1%BB%A9c_Th%E1%BA%AFng',
    'verified': True}]),
 ('Bảo tàng Hồ Chí Minh',
  ('museum',),
  10.7683,
  106.7068,
  'historical',
  'Bảo tàng đặt tại Nhà Rồng, nơi ngày 5/6/1911 Nguyễn Tất Thành xuống tàu Amiral Latouche-Tréville bắt đầu hành trình tìm đường cứu nước.',
  'https://vi.wikipedia.org/wiki/B%E1%BA%BFn_Nh%C3%A0_R%E1%BB%93ng',
  None,
  'Nhà Rồng vốn là trụ sở một hãng vận tải biển của Pháp, xây từ những năm đầu thực dân Pháp chiếm Sài Gòn; sau năm 1975 được giữ gìn làm '
  'khu lưu niệm và từ năm 1995 là Bảo tàng Hồ Chí Minh – Chi nhánh TP.HCM.',
  'https://baovanhoa.vn/du-lich/cong-trinh-giua-trung-tam-tphcm-gan-su-kien-lich-su-hon-100-nam-truoc-234410.html',
  [{'title': 'Nguyễn Tất Thành ra đi tìm đường cứu nước (5/6/1911)',
    'description': 'Nguyễn Tất Thành, sau này là Hồ Chí Minh, xuống tàu Amiral Latouche-Tréville tại bến Nhà Rồng để sang phương Tây.',
    'source': 'https://vi.wikipedia.org/wiki/B%E1%BA%BFn_Nh%C3%A0_R%E1%BB%93ng',
    'verified': True},
   {'title': 'Trở thành bảo tàng (1995)',
    'description': 'Từ năm 1995 Nhà Rồng hoạt động với tên Bảo tàng Hồ Chí Minh – Chi nhánh TP.HCM, sưu tầm và trưng bày tư liệu về cuộc '
                   'đời hoạt động cách mạng của Hồ Chủ tịch.',
    'source': 'https://baovanhoa.vn/du-lich/cong-trinh-giua-trung-tam-tphcm-gan-su-kien-lich-su-hon-100-nam-truoc-234410.html',
    'verified': True}],
  [{'title': 'Lưỡng long chầu nguyệt',
    'description': 'Trên nóc tòa nhà có hai con rồng đất nung tráng men xanh theo mô típ lưỡng long chầu nguyệt, nên người dân gọi là Nhà '
                   'Rồng.',
    'source': 'https://vi.wikipedia.org/wiki/B%E1%BA%BFn_Nh%C3%A0_R%E1%BB%93ng',
    'verified': True},
   {'title': 'Hơn 24.000 hiện vật',
    'description': 'Theo Báo Tri thức - Znews, bảo tàng lưu giữ hơn 24.000 hiện vật, tài liệu, hình ảnh.',
    'source': 'https://znews.vn/tu-noi-nay-bac-da-ra-di-post1647034.html',
    'verified': True}]),
 ('Công viên Bến Bạch Đằng',
  ('park',),
  10.7739,
  106.7073,
  'nature',
  'Khu công viên và bến sông bên bờ sông Sài Gòn dọc đường Tôn Đức Thắng, Quận 1, là nơi dạo bờ sông giữa trung tâm thành phố.',
  'https://vi.wikipedia.org/wiki/B%E1%BA%BFn_B%E1%BA%A1ch_%C4%90%E1%BA%B1ng',
  None,
  'Giai đoạn 1865–1920 bờ sông này mang các tên tiếng Pháp như Quai Napoléon hay Quai Francis Garnier; năm 1955 đổi thành Bến Bạch Đằng và '
  'năm 1980 nhập vào đường Tôn Đức Thắng.',
  'https://vi.wikipedia.org/wiki/B%E1%BA%BFn_B%E1%BA%A1ch_%C4%90%E1%BA%B1ng',
  [{'title': 'Khánh thành công viên sau chỉnh trang (17/3/2022)',
    'description': 'Ngày 17/3/2022 TP.HCM khánh thành công viên Bến Bạch Đằng cùng công viên Mê Linh sau khi cải tạo.',
    'source': 'https://www.sggp.org.vn/khanh-thanh-cong-vien-ben-bach-dang-va-cong-vien-me-linh-post630120.html',
    'verified': True}],
  [{'title': 'Quy mô cải tạo',
    'description': 'Phần công viên được chỉnh trang rộng khoảng 1,6 ha, gồm khoảng 8.700 m² đường dạo, sân sinh hoạt lát đá granite và '
                   '7.000 m² cây xanh.',
    'source': 'https://www.sggp.org.vn/khanh-thanh-cong-vien-ben-bach-dang-va-cong-vien-me-linh-post630120.html',
    'verified': True},
   {'title': 'Bến buýt sông',
    'description': 'Khu vực có bến buýt sông, nơi các tuyến buýt sông của thành phố hoạt động.',
    'source': 'https://vi.wikipedia.org/wiki/B%E1%BA%BFn_B%E1%BA%A1ch_%C4%90%E1%BA%B1ng',
    'verified': True}]),
 ('Thư viện Khoa học Tổng hợp Thành phố Hồ Chí Minh',
  ('library',),
  10.775,
  106.6989,
  'historical',
  'Thư viện công cộng tại số 69 Lý Tự Trọng, Quận 1, là một trong những thư viện lâu đời nhất Việt Nam, có tiền thân từ năm 1868.',
  'https://vi.wikipedia.org/wiki/Th%C6%B0_vi%E1%BB%87n_Khoa_h%E1%BB%8Dc_T%E1%BB%95ng_h%E1%BB%A3p_Th%C3%A0nh_ph%E1%BB%91_H%E1%BB%93_Ch%C3%AD_Minh',
  None,
  'Tiền thân là thư viện tư liệu do Thống đốc Nam Kỳ Gustave Ohier lập năm 1868; tòa nhà hiện nay khánh thành ngày 23/12/1971 trên nền '
  'Khám Lớn Sài Gòn cũ và mang tên hiện tại từ ngày 14/4/1978.',
  'https://vi.wikipedia.org/wiki/Th%C6%B0_vi%E1%BB%87n_Khoa_h%E1%BB%8Dc_T%E1%BB%95ng_h%E1%BB%A3p_Th%C3%A0nh_ph%E1%BB%91_H%E1%BB%93_Ch%C3%AD_Minh',
  [{'title': 'Thư viện tư liệu đầu tiên (1868)',
    'description': 'Thống đốc Nam Kỳ Gustave Ohier cho lập Thư viện Tư liệu Chính phủ Nam Kỳ, tiền thân của thư viện ngày nay.',
    'source': 'https://vi.wikipedia.org/wiki/Th%C6%B0_vi%E1%BB%87n_Khoa_h%E1%BB%8Dc_T%E1%BB%95ng_h%E1%BB%A3p_Th%C3%A0nh_ph%E1%BB%91_H%E1%BB%93_Ch%C3%AD_Minh',
    'verified': True},
   {'title': 'Khánh thành tòa nhà 16 tầng (23/12/1971)',
    'description': 'Tòa nhà cao 16 tầng của Thư viện Quốc gia được khánh thành ngày 23/12/1971.',
    'source': 'https://vi.wikipedia.org/wiki/Th%C6%B0_vi%E1%BB%87n_Khoa_h%E1%BB%8Dc_T%E1%BB%95ng_h%E1%BB%A3p_Th%C3%A0nh_ph%E1%BB%91_H%E1%BB%93_Ch%C3%AD_Minh',
    'verified': True},
   {'title': 'Mang tên Thư viện Khoa học Tổng hợp (14/4/1978)',
    'description': 'Năm 1978 thư viện hợp nhất với Thư viện Khoa học Kỹ thuật và lấy tên Thư viện Khoa học Tổng hợp.',
    'source': 'https://vi.wikipedia.org/wiki/Th%C6%B0_vi%E1%BB%87n_Khoa_h%E1%BB%8Dc_T%E1%BB%95ng_h%E1%BB%A3p_Th%C3%A0nh_ph%E1%BB%91_H%E1%BB%93_Ch%C3%AD_Minh',
    'verified': True}],
  [{'title': 'Xây trên nền Khám Lớn Sài Gòn',
    'description': 'Thư viện nằm ở vị trí của Khám Lớn (Maison Centrale), nhà tù thời thuộc địa từng chiếm gần trọn khu đất giữa các đường '
                   'Lý Tự Trọng, Nam Kỳ Khởi Nghĩa, Lê Thánh Tôn và Nguyễn Trung Trực.',
    'source': 'https://www.saigoneer.com/saigon-heritage/2674-old-saigon-building-of-the-week-ho-chi-minh-city-general-sciences-library',
    'verified': True},
   {'title': 'Nhiều lần đổi tên',
    'description': 'Thư viện từng mang tên Thư viện Sài Gòn (1882), Thư viện Nam Kỳ (1902), Thư viện Quốc gia (1957) trước khi thành Thư '
                   'viện Khoa học Tổng hợp.',
    'source': 'https://www.saigoneer.com/saigon-heritage/2674-old-saigon-building-of-the-week-ho-chi-minh-city-general-sciences-library',
    'verified': True}]),
 ('Nhà hát Thành phố',
  ('theatre',),
  10.7765,
  106.7033,
  'architectural',
  'Nhà hát khánh thành ngày 1/1/1900 theo lối kiến trúc flamboyant của thời Đệ tam Cộng hòa Pháp, hiện là nhà hát đa năng trung tâm của '
  'thành phố.',
  'https://vi.wikipedia.org/wiki/Nh%C3%A0_h%C3%A1t_Th%C3%A0nh_ph%E1%BB%91_H%E1%BB%93_Ch%C3%AD_Minh',
  None,
  'Công trình khởi công năm 1898 và khánh thành ngày 1/1/1900, do ba kiến trúc sư Félix Olivier, Ernest Guichard và Eugène Ferret thiết '
  'kế.',
  'https://vi.wikipedia.org/wiki/Nh%C3%A0_h%C3%A1t_Th%C3%A0nh_ph%E1%BB%91_H%E1%BB%93_Ch%C3%AD_Minh',
  [{'title': 'Trụ sở Quốc hội thời Việt Nam Cộng hòa (1955-1975)',
    'description': 'Sau khi tu bổ năm 1955, tòa nhà được dùng làm trụ sở Quốc hội (về sau gọi là Hạ nghị viện) của chính quyền Việt Nam '
                   'Cộng hòa, trước khi trở lại chức năng biểu diễn.',
    'source': 'https://vi.wikipedia.org/wiki/Nh%C3%A0_h%C3%A1t_Th%C3%A0nh_ph%E1%BB%91_H%E1%BB%93_Ch%C3%AD_Minh',
    'verified': True},
   {'title': 'Phục hồi trang trí năm 1998',
    'description': 'Nhân dịp kỷ niệm 300 năm Sài Gòn, thành phố tu bổ và khôi phục các trang trí cũ của nhà hát với kinh phí khoảng 25 tỷ '
                   'đồng.',
    'source': 'https://vi.wikipedia.org/wiki/Nh%C3%A0_h%C3%A1t_Th%C3%A0nh_ph%E1%BB%91_H%E1%BB%93_Ch%C3%AD_Minh',
    'verified': True}],
  [{'title': 'Số chỗ ngồi thay đổi',
    'description': 'Nhà hát ban đầu có 559 chỗ ngồi; sau đợt cải tạo 2007-2009 còn khoảng 468 chỗ.',
    'source': 'https://vi.wikipedia.org/wiki/Nh%C3%A0_h%C3%A1t_Th%C3%A0nh_ph%E1%BB%91_H%E1%BB%93_Ch%C3%AD_Minh',
    'verified': True}]),
 ('Trụ sở Ủy ban nhân dân Thành phố Hồ Chí Minh',
  ('government',),
  10.7766,
  106.701,
  'architectural',
  'Công trình thời Pháp thuộc gọi là Hôtel de ville (dân gian gọi là Dinh xã Tây), nay là trụ sở Ủy ban nhân dân Thành phố Hồ Chí Minh.',
  'https://vi.wikipedia.org/wiki/Tr%E1%BB%A5_s%E1%BB%9F_%E1%BB%A6y_ban_nh%C3%A2n_d%C3%A2n_Th%C3%A0nh_ph%E1%BB%91_H%E1%BB%93_Ch%C3%AD_Minh',
  None,
  'Tòa nhà do kiến trúc sư Fernand Gardè thiết kế, xây dựng từ năm 1898 đến 1908 và khánh thành năm 1909; thời Việt Nam Cộng hòa gọi là '
  'Tòa đô chánh Sài Gòn.',
  'https://vi.wikipedia.org/wiki/Tr%E1%BB%A5_s%E1%BB%9F_%E1%BB%A6y_ban_nh%C3%A2n_d%C3%A2n_Th%C3%A0nh_ph%E1%BB%91_H%E1%BB%93_Ch%C3%AD_Minh',
  [{'title': 'Ra mắt Ủy ban Hành chính Lâm thời Nam Bộ (25/8/1945)',
    'description': 'Ngày 25/8/1945 Ủy ban Hành chính Lâm thời Nam Bộ ra mắt tại khu vực này; trong vườn hoa trước trụ sở có bia lưu niệm '
                   'sự kiện.',
    'source': 'https://vi.wikipedia.org/wiki/Tr%E1%BB%A5_s%E1%BB%9F_%E1%BB%A6y_ban_nh%C3%A2n_d%C3%A2n_Th%C3%A0nh_ph%E1%BB%91_H%E1%BB%93_Ch%C3%AD_Minh',
    'verified': True}],
  [{'title': 'Di tích cấp quốc gia và lần đầu mở cửa đón khách',
    'description': 'Năm 2020 tòa nhà được xếp hạng di tích kiến trúc nghệ thuật cấp quốc gia; dịp lễ 30/4 năm 2023 trụ sở lần đầu tiên đón '
                   'khách tham quan.',
    'source': 'https://vi.wikipedia.org/wiki/Tr%E1%BB%A5_s%E1%BB%9F_%E1%BB%A6y_ban_nh%C3%A2n_d%C3%A2n_Th%C3%A0nh_ph%E1%BB%91_H%E1%BB%93_Ch%C3%AD_Minh',
    'verified': True}]),
 ('Nhà thờ Tân Định',
  ('place_of_worship',),
  10.7883,
  106.6907,
  'architectural',
  'Nhà thờ Tân Định ở số 289 Hai Bà Trưng, nổi tiếng với màu hồng đặc trưng, được xây theo phong cách Roman kết hợp các yếu tố Gothic.',
  'https://vi.wikipedia.org/wiki/Nh%C3%A0_th%E1%BB%9D_T%C3%A2n_%C4%90%E1%BB%8Bnh',
  None,
  'Nhà thờ khởi công năm 1870 và được làm phép ngày 16/12/1876, do linh mục Donatien Éveillard coi sóc việc xây dựng.',
  'https://vi.wikipedia.org/wiki/Nh%C3%A0_th%E1%BB%9D_T%C3%A2n_%C4%90%E1%BB%8Bnh',
  [{'title': 'Sơn màu hồng năm 1957',
    'description': "Năm 1957 nhà thờ được sơn màu hồng, từ đó có biệt danh 'nhà thờ Hồng'.",
    'source': 'https://vi.wikipedia.org/wiki/Nh%C3%A0_th%E1%BB%9D_T%C3%A2n_%C4%90%E1%BB%8Bnh',
    'verified': True}],
  [{'title': 'Tháp chuông',
    'description': 'Tháp chính cao khoảng 52,6 m, trên đỉnh có cây thánh giá bằng đồng cao 3 m.',
    'source': 'https://vi.wikipedia.org/wiki/Nh%C3%A0_th%E1%BB%9D_T%C3%A2n_%C4%90%E1%BB%8Bnh',
    'verified': True},
   {'title': 'Nội thất',
    'description': 'Nhà thờ có bàn thờ chính bằng đá cẩm thạch Ý và năm quả chuông tổng nặng khoảng 5,5 tấn.',
    'source': 'https://vi.wikipedia.org/wiki/Nh%C3%A0_th%E1%BB%9D_T%C3%A2n_%C4%90%E1%BB%8Bnh',
    'verified': True}]),
 ('Nhà thờ Huyện Sỹ',
  ('place_of_worship',),
  10.7686,
  106.689,
  'architectural',
  'Nhà thờ Huyện Sỹ có tên chính thức là Nhà thờ Thánh Philipphê Tông đồ, nằm tại số 1 Tôn Thất Tùng, xây theo phong cách Gothic.',
  'https://vi.wikipedia.org/wiki/Nh%C3%A0_th%E1%BB%9D_Huy%E1%BB%87n_S%E1%BB%B9',
  None,
  'Nhà thờ được xây từ năm 1902 đến 1905 và làm phép năm 1905, trên phần đất do ông Lê Phát Đạt (Huyện Sỹ) hiến tặng.',
  'https://vi.wikipedia.org/wiki/Nh%C3%A0_th%E1%BB%9D_Huy%E1%BB%87n_S%E1%BB%B9',
  [{'title': 'Hiến đất và đóng góp xây nhà thờ',
    'description': 'Ông Lê Phát Đạt (Huyện Sỹ) hiến đất và góp một phần bảy gia sản để xây nhà thờ, nên nhà thờ mang tên ông theo cách gọi '
                   'dân gian.',
    'source': 'https://vi.wikipedia.org/wiki/Nh%C3%A0_th%E1%BB%9D_Huy%E1%BB%87n_S%E1%BB%B9',
    'verified': True}],
  [{'title': 'Tên gọi dân gian khác tên thánh bổn mạng',
    'description': 'Dù thường gọi là nhà thờ Huyện Sỹ, vị thánh bổn mạng thực tế là Thánh Philipphê Tông đồ chứ không phải người hiến đất.',
    'source': 'https://vi.wikipedia.org/wiki/Nh%C3%A0_th%E1%BB%9D_Huy%E1%BB%87n_S%E1%BB%B9',
    'verified': True},
   {'title': 'Chuông và kính màu',
    'description': 'Nhà thờ có bốn quả chuông đồng đúc tại Pháp năm 1905 và các ô kính màu nhập từ Ý; tổng chiều cao tính cả thánh giá và '
                   'gà trống khoảng 57 m.',
    'source': 'https://vi.wikipedia.org/wiki/Nh%C3%A0_th%E1%BB%9D_Huy%E1%BB%87n_S%E1%BB%B9',
    'verified': True}]),
 ('Nhà thờ Chợ Quán',
  ('place_of_worship',),
  10.7573,
  106.6817,
  'historical',
  'Nhà thờ Chợ Quán (tên chính thức Nhà thờ Thánh Tâm Chúa Giêsu) tại 120 Trần Bình Trọng, được xem là nhà thờ cổ nhất thành phố hiện nay.',
  'https://vi.wikipedia.org/wiki/Nh%C3%A0_th%E1%BB%9D_Ch%E1%BB%A3_Qu%C3%A1n',
  None,
  'Nhà thờ hiện tại được khởi công năm 1882 và khánh thành vào mùng 4 Tết Bính Thân (1896), sau nhiều lần xây lại trên cùng vùng đất giáo '
  'xứ có từ trước.',
  'https://vi.wikipedia.org/wiki/Nh%C3%A0_th%E1%BB%9D_Ch%E1%BB%A3_Qu%C3%A1n',
  [{'title': 'Nhiều lần xây lại',
    'description': 'Nhà thờ ở khu vực này nhiều lần bị phá hủy và được xây lại trước khi có công trình hiện nay.',
    'source': 'https://vi.wikipedia.org/wiki/Nh%C3%A0_th%E1%BB%9D_Ch%E1%BB%A3_Qu%C3%A1n',
    'verified': True},
   {'title': 'Khánh thành công trình hiện tại',
    'description': 'Linh mục Nicôla Hamm khởi công năm 1882; sau khi ông qua đời, các linh mục Errard rồi Lucien Mossard tiếp tục và hoàn '
                   'thành công trình.',
    'source': 'https://vi.wikipedia.org/wiki/Nh%C3%A0_th%E1%BB%9D_Ch%E1%BB%A3_Qu%C3%A1n',
    'verified': True}],
  [{'title': 'Phong cách Romanesque',
    'description': 'Nhà thờ mang phong cách Romanesque với cửa vòm cong, cột đá lớn, mái ngói đỏ và tháp chuông ba tầng chứa năm quả '
                   'chuông.',
    'source': 'https://vi.wikipedia.org/wiki/Nh%C3%A0_th%E1%BB%9D_Ch%E1%BB%A3_Qu%C3%A1n',
    'verified': True}]),
 ('Masjid Jamia al-Muslimin',
  ('place_of_worship',),
  10.7762,
  106.7043,
  'cultural',
  'Đây là thánh đường Hồi giáo Jamia Al-Muslimin (còn gọi là Saigon Central Mosque, tên gọi tại chỗ là Thánh đường Hồi giáo Ấn Độ '
  'Musulman) ở số 66 Đông Du, quận 1, xây dựng năm 1935.',
  'https://en.wikipedia.org/wiki/Saigon_Central_Mosque',
  None,
  'Công trình khởi công ngày 21/12/1934 và hoàn thành năm 1935 dưới sự chỉ đạo của ông J.M. Mohamed Ismael, người đứng đầu cộng đồng Hồi '
  'giáo Ấn Độ thời đó.',
  'https://en.wikipedia.org/wiki/Saigon_Central_Mosque',
  [{'title': 'Nehru thăm thánh đường (17/10/1954)',
    'description': 'Thủ tướng Ấn Độ Jawaharlal Nehru cùng Indira Gandhi từng đến thăm thánh đường và dự buổi họp của cộng đồng người Ấn '
                   'tại đây.',
    'source': 'https://en.wikipedia.org/wiki/Saigon_Central_Mosque',
    'verified': True}],
  [{'title': 'Kiến trúc',
    'description': 'Thánh đường có bốn tháp minaret và bốn lối vào.',
    'source': 'https://en.wikipedia.org/wiki/Saigon_Central_Mosque',
    'verified': True}]),
 ('Landmark 81 Skyview',
  ('landmark',),
  10.7944,
  106.7217,
  'architectural',
  'Landmark 81 là tòa nhà cao 461,2 m, 81 tầng (gồm 3 tầng hầm), và là công trình cao nhất Việt Nam từ tháng 2/2018, có đài quan sát '
  'Skyview ở các tầng cao nhất.',
  'https://vi.wikipedia.org/wiki/Landmark_81',
  None,
  'Tòa nhà khởi công ngày 26/7/2014 và khánh thành ngày 26/7/2018 sau 1.461 ngày thi công; đơn vị thiết kế là công ty Atkins của Anh.',
  'https://vi.wikipedia.org/wiki/Landmark_81',
  [{'title': 'Khai trương đài quan sát Skyview (28/4/2019)',
    'description': 'Đài quan sát Skyview khánh thành ngày 28/4/2019, nằm ở các tầng 79-81 và được giới thiệu là đài quan sát cao nhất Việt '
                   'Nam và Đông Nam Á vào thời điểm đó.',
    'source': 'https://vi.wikipedia.org/wiki/Landmark_81',
    'verified': True}],
  [{'title': 'Cảm hứng từ bó tre',
    'description': 'Thiết kế của tòa nhà lấy cảm hứng từ những bó tre truyền thống, tượng trưng cho sức mạnh và sự đoàn kết trong văn hóa '
                   'Việt Nam.',
    'source': 'https://vi.wikipedia.org/wiki/Landmark_81',
    'verified': True},
   {'title': 'Vượt Bitexco',
    'description': 'Từ tháng 2/2018 Landmark 81 vượt Tháp Tài chính Bitexco để trở thành công trình cao nhất Việt Nam.',
    'source': 'https://vi.wikipedia.org/wiki/Landmark_81',
    'verified': True}]),
 ('Cầu Mống',
  ('landmark',),
  10.7681,
  106.7037,
  'historical',
  'Cầu Mống là cây cầu thép vòm bắc qua kênh Bến Nghé, nối quận 1 và quận 4, được xây vào năm 1893-1894 và là một trong những cây cầu cổ '
  'nhất thành phố.',
  'https://vi.wikipedia.org/wiki/C%E1%BA%A7u_M%E1%BB%91ng',
  None,
  'Cầu do công ty vận chuyển hàng hải Messageries Maritimes của Pháp bỏ vốn xây dựng, dài khoảng 128 m, rộng 5,2 m.',
  'https://vi.wikipedia.org/wiki/C%E1%BA%A7u_M%E1%BB%91ng',
  [{'title': 'Tháo dỡ và lắp lại khi làm Đại lộ Đông - Tây',
    'description': 'Khi thi công Đại lộ Đông - Tây và hầm sông Sài Gòn, cầu được tháo dỡ hoàn toàn rồi lắp ghép lại theo nguyên bản, gia '
                   'cố thêm móng trụ và bổ sung chiếu sáng mỹ thuật.',
    'source': 'https://vi.wikipedia.org/wiki/C%E1%BA%A7u_M%E1%BB%91ng',
    'verified': True}],
  [{'title': 'Nguồn gốc tên gọi',
    'description': 'Cầu làm theo kiểu vồng mống nên dân gian gọi là cầu Mống; người Pháp gọi là Arc-en-ciel (cầu vồng).',
    'source': 'https://vi.wikipedia.org/wiki/C%E1%BA%A7u_M%E1%BB%91ng',
    'verified': True}]),
 ('Hội quán Tuệ Thành',
  ('place_of_worship',),
  10.7535,
  106.6612,
  'cultural',
  'Hội quán của người Hoa gốc Quảng Châu (Tuệ Thành) ở Chợ Lớn, thờ bà Thiên Hậu – vị nữ thần bảo hộ người đi biển – và được xếp hạng di '
  'tích kiến trúc nghệ thuật quốc gia.',
  'https://vi.wikipedia.org/wiki/H%E1%BB%99i_qu%C3%A1n_Tu%E1%BB%87_Th%C3%A0nh',
  None,
  'Do người Hoa từ Quảng Châu lập nên, là một trong những nơi thờ tự lâu đời nhất của người Hoa ở khu Chợ Lớn cũ; năm xây dựng chưa xác '
  'định chắc chắn, một số ý kiến cho rằng khoảng năm 1760.',
  'https://vi.wikipedia.org/wiki/H%E1%BB%99i_qu%C3%A1n_Tu%E1%BB%87_Th%C3%A0nh',
  [{'title': 'Xếp hạng di tích quốc gia (7/1/1993)',
    'description': 'Hội quán được công nhận là di tích kiến trúc nghệ thuật quốc gia vào ngày 7/1/1993.',
    'source': 'https://vi.wikipedia.org/wiki/H%E1%BB%99i_qu%C3%A1n_Tu%E1%BB%87_Th%C3%A0nh',
    'verified': True}],
  [{'title': 'Lễ hội Vía Bà',
    'description': 'Lễ hội chính diễn ra vào ngày 23 tháng 3 âm lịch, ngày được coi là sinh nhật của bà Thiên Hậu, với các nghi thức như '
                   'rước kiệu và biểu diễn truyền thống.',
    'source': 'https://vi.wikipedia.org/wiki/H%E1%BB%99i_qu%C3%A1n_Tu%E1%BB%87_Th%C3%A0nh',
    'verified': True},
   {'title': 'Kiến trúc chữ khẩu',
    'description': 'Công trình theo kiểu Trung Hoa truyền thống, gồm tiền điện, trung điện và hậu điện nối với nhau qua các sân trời, '
                   'trang trí bằng tượng gốm và phù điêu.',
    'source': 'https://vi.wikipedia.org/wiki/H%E1%BB%99i_qu%C3%A1n_Tu%E1%BB%87_Th%C3%A0nh',
    'verified': True},
   {'title': 'Khoảng 400 cổ vật',
    'description': 'Hội quán còn lưu giữ khoảng 400 hiện vật, trong đó có chuông đồng niên đại 1796 và 1830 cùng nhiều kiệu và đồ tế khí.',
    'source': 'https://vi.wikipedia.org/wiki/H%E1%BB%99i_qu%C3%A1n_Tu%E1%BB%87_Th%C3%A0nh',
    'verified': True}]),
 ('Hội quán Nghĩa An',
  ('place_of_worship',),
  10.7537,
  106.6621,
  'cultural',
  'Hội quán của người Hoa Triều Châu ở Chợ Lớn, thờ Quan Công, còn được gọi là Chùa Ông hay miếu Quan Đế.',
  'https://vi.wikipedia.org/wiki/H%E1%BB%99i_qu%C3%A1n_Ngh%C4%A9a_An',
  None,
  'Được lập từ cuối thế kỷ 18 bởi cộng đồng người Hoa Triều Châu và hoàn thành vào khoảng năm 1819-1820.',
  'https://vi.wikipedia.org/wiki/H%E1%BB%99i_qu%C3%A1n_Ngh%C4%A9a_An',
  [{'title': 'Xếp hạng di tích quốc gia (7/11/1993)',
    'description': 'Bộ Văn hóa - Thông tin công nhận hội quán là di tích kiến trúc nghệ thuật quốc gia ngày 7/11/1993.',
    'source': 'https://vi.wikipedia.org/wiki/H%E1%BB%99i_qu%C3%A1n_Ngh%C4%A9a_An',
    'verified': True},
   {'title': 'Nhiều lần trùng tu',
    'description': 'Công trình được trùng tu nhiều lần; đợt gần nhất được ghi nhận kéo dài từ năm 2009 đến 2014.',
    'source': 'https://vi.wikipedia.org/wiki/H%E1%BB%99i_qu%C3%A1n_Ngh%C4%A9a_An',
    'verified': True}],
  [{'title': 'Tượng Quan Công cao 3 mét',
    'description': 'Trong hội quán có tượng Quan Vũ bằng thạch cao cao khoảng 3 mét.',
    'source': 'https://vi.wikipedia.org/wiki/H%E1%BB%99i_qu%C3%A1n_Ngh%C4%A9a_An',
    'verified': True},
   {'title': 'Phong cách Triều Châu',
    'description': 'Kiến trúc mang phong cách Triều Châu với màu đỏ chủ đạo, nhiều chạm khắc gỗ, đá và đồ đồng trang trí từ thế kỷ 19; '
                   'khuôn viên rộng khoảng 2.000 m².',
    'source': 'https://vi.wikipedia.org/wiki/H%E1%BB%99i_qu%C3%A1n_Ngh%C4%A9a_An',
    'verified': True}]),
 ('Chùa Vĩnh Nghiêm',
  ('place_of_worship',),
  10.7904,
  106.6823,
  'architectural',
  'Ngôi chùa lớn ở đường Nam Kỳ Khởi Nghĩa do hai vị hòa thượng miền Bắc là Thích Tâm Giác và Thích Thanh Kiểm khởi xướng xây dựng, mang '
  'kiến trúc truyền thống Bắc Bộ kết hợp kỹ thuật xây dựng hiện đại.',
  'https://vi.wikipedia.org/wiki/Ch%C3%B9a_V%C4%A9nh_Nghi%C3%AAm_(Th%C3%A0nh_ph%E1%BB%91_H%E1%BB%93_Ch%C3%AD_Minh)',
  None,
  'Chùa khởi công năm 1964 trên vùng đất trũng gần kênh Thị Nghè và về cơ bản hoàn thành các hạng mục chính vào năm 1971.',
  'https://vi.wikipedia.org/wiki/Ch%C3%B9a_V%C4%A9nh_Nghi%C3%AAm_(Th%C3%A0nh_ph%E1%BB%91_H%E1%BB%93_Ch%C3%AD_Minh)',
  [{'title': 'Khởi công năm 1964',
    'description': 'Việc xây dựng bắt đầu từ năm 1964 và phải san lấp khoảng 40.000 m³ đất cho vùng trũng ven kênh Thị Nghè.',
    'source': 'https://vi.wikipedia.org/wiki/Ch%C3%B9a_V%C4%A9nh_Nghi%C3%AAm_(Th%C3%A0nh_ph%E1%BB%91_H%E1%BB%93_Ch%C3%AD_Minh)',
    'verified': True},
   {'title': 'Hoàn thành tháp đá (2003)',
    'description': 'Tháp đá cao 14 mét được hoàn thành vào cuối năm 2003.',
    'source': 'https://vi.wikipedia.org/wiki/Ch%C3%B9a_V%C4%A9nh_Nghi%C3%AAm_(Th%C3%A0nh_ph%E1%BB%91_H%E1%BB%93_Ch%C3%AD_Minh)',
    'verified': True}],
  [{'title': 'Tháp Quán Thế Âm 7 tầng',
    'description': 'Tháp Quán Thế Âm gồm bảy tầng, cao gần 40 mét, được xây cùng quần thể chính.',
    'source': 'https://vi.wikipedia.org/wiki/Ch%C3%B9a_V%C4%A9nh_Nghi%C3%AAm_(Th%C3%A0nh_ph%E1%BB%91_H%E1%BB%93_Ch%C3%AD_Minh)',
    'verified': True},
   {'title': 'Tháp đá lớn',
    'description': 'Theo Wikipedia, tính đến năm 2013 đây là ngôi tháp đá lớn nhất và cao nhất Việt Nam.',
    'source': 'https://vi.wikipedia.org/wiki/Ch%C3%B9a_V%C4%A9nh_Nghi%C3%AAm_(Th%C3%A0nh_ph%E1%BB%91_H%E1%BB%93_Ch%C3%AD_Minh)',
    'verified': True},
   {'title': 'Kiến trúc sư và đại hồng chung',
    'description': 'Chùa do kiến trúc sư Nguyễn Bá Lăng thiết kế, có một quả chuông hòa bình đúc năm 1971 do Phật tử Nhật Bản tặng.',
    'source': 'https://vi.wikipedia.org/wiki/Ch%C3%B9a_V%C4%A9nh_Nghi%C3%AAm_(Th%C3%A0nh_ph%E1%BB%91_H%E1%BB%93_Ch%C3%AD_Minh)',
    'verified': True}]),
 ('Chùa Giác Lâm',
  ('place_of_worship',),
  10.778,
  106.6492,
  'historical',
  'Một trong những ngôi chùa cổ nhất Thành phố Hồ Chí Minh, nằm ở đường Lạc Long Quân, được lập năm 1744 và là di tích lịch sử - văn hóa '
  'quốc gia.',
  'https://vi.wikipedia.org/wiki/Ch%C3%B9a_Gi%C3%A1c_L%C3%A2m',
  None,
  'Chùa do cư sĩ Lý Thụy Long lập năm 1744 dưới thời chúa Nguyễn Phúc Khoát; năm 1774 tổ Viên Quang về trụ trì và chùa mang tên Giác Lâm, '
  'trở thành trung tâm của thiền phái Lâm Tế ở phía Nam.',
  'https://vi.wikipedia.org/wiki/Ch%C3%B9a_Gi%C3%A1c_L%C3%A2m',
  [{'title': 'Ba đợt đại trùng tu',
    'description': 'Chùa trải qua ba lần đại trùng tu: 1798-1804, 1906-1909 và hoàn tất năm 1999.',
    'source': 'https://vi.wikipedia.org/wiki/Ch%C3%B9a_Gi%C3%A1c_L%C3%A2m',
    'verified': True},
   {'title': 'Xếp hạng di tích quốc gia (1988)',
    'description': 'Chùa được Bộ Văn hóa xếp hạng di tích lịch sử - văn hóa quốc gia theo quyết định ngày 16/11/1988.',
    'source': 'https://vi.wikipedia.org/wiki/Ch%C3%B9a_Gi%C3%A1c_L%C3%A2m',
    'verified': True}],
  [{'title': '113 pho tượng cổ',
    'description': 'Chùa lưu giữ 113 pho tượng cổ, phần lớn bằng gỗ, kèm 7 tượng đồng; trên cột chính có 86 câu liễn đối.',
    'source': 'https://vi.wikipedia.org/wiki/Ch%C3%B9a_Gi%C3%A1c_L%C3%A2m',
    'verified': True},
   {'title': 'Cây bồ đề từ Sri Lanka',
    'description': 'Một cây bồ đề từ Sri Lanka được trồng tại chùa ngày 18/6/1953.',
    'source': 'https://vi.wikipedia.org/wiki/Ch%C3%B9a_Gi%C3%A1c_L%C3%A2m',
    'verified': True},
   {'title': 'Tháp lục giác 7 tầng',
    'description': 'Bảo tháp lục giác bảy tầng được xây từ năm 1970 và hoàn tất năm 1994.',
    'source': 'https://vi.wikipedia.org/wiki/Ch%C3%B9a_Gi%C3%A1c_L%C3%A2m',
    'verified': True}]),
 ('Chùa Ngọc Hoàng',
  ('place_of_worship',),
  10.7915,
  106.6977,
  'cultural',
  'Ngôi chùa kiểu Hoa ở đường Mai Thị Lựu, thờ Ngọc Hoàng Thượng đế, tên chính thức là Phước Hải tự và từng được người Pháp gọi là chùa Đa '
  'Kao.',
  'https://vi.wikipedia.org/wiki/Ch%C3%B9a_Ng%E1%BB%8Dc_Ho%C3%A0ng',
  None,
  'Chùa do người Hoa tên Lưu Minh (pháp danh Lưu Đạo Nguyên) dựng vào khoảng đầu thế kỷ 20; các tài liệu ghi năm khởi dựng khác nhau.',
  'https://vi.wikipedia.org/wiki/Ch%C3%B9a_Ng%E1%BB%8Dc_Ho%C3%A0ng',
  [{'title': 'Nơi hội kín thuở ban đầu',
    'description': 'Theo học giả Vương Hồng Sển, ngoài thờ phụng, người sáng lập còn dùng chùa làm nơi hội kín, có thể gắn với hoạt động '
                   'chống nhà Thanh.',
    'source': 'https://vi.wikipedia.org/wiki/Ch%C3%B9a_Ng%E1%BB%8Dc_Ho%C3%A0ng',
    'verified': True},
   {'title': 'Đổi tên Phước Hải tự (1984)',
    'description': 'Từ năm 1982 chùa do hòa thượng Thích Vĩnh Khương quản lý và thuộc Giáo hội Phật giáo Việt Nam; năm 1984 chùa được đổi '
                   'tên thành Phước Hải tự.',
    'source': 'https://vi.wikipedia.org/wiki/Ch%C3%B9a_Ng%E1%BB%8Dc_Ho%C3%A0ng',
    'verified': True},
   {'title': 'Xếp hạng di tích (15/10/1994)',
    'description': 'Chùa được công nhận là di tích kiến trúc nghệ thuật cấp quốc gia ngày 15/10/1994.',
    'source': 'https://vi.wikipedia.org/wiki/Ch%C3%B9a_Ng%E1%BB%8Dc_Ho%C3%A0ng',
    'verified': True}],
  [{'title': 'Cổng tam quan hai rồng',
    'description': 'Cổng tam quan có hình hai rồng uốn lượn trong thế tranh châu.',
    'source': 'https://vi.wikipedia.org/wiki/Ch%C3%B9a_Ng%E1%BB%8Dc_Ho%C3%A0ng',
    'verified': True},
   {'title': 'Khuôn viên khoảng 2.300 m²',
    'description': 'Chùa có diện tích khoảng 2.300 m², mái lợp ngói âm dương và nhiều tượng gỗ trang trí công phu.',
    'source': 'https://vi.wikipedia.org/wiki/Ch%C3%B9a_Ng%E1%BB%8Dc_Ho%C3%A0ng',
    'verified': True}]),
 ('Chùa Phật Học Xá Lợi',
  ('place_of_worship',),
  10.7781,
  106.6865,
  'historical',
  'Chùa Xá Lợi ở đường Bà Huyện Thanh Quan được xây để thờ xá lợi Phật, là ngôi chùa đầu tiên của thành phố theo lối kiến trúc hiện đại và '
  'là di tích cấp thành phố.',
  'https://vi.wikipedia.org/wiki/Ch%C3%B9a_X%C3%A1_L%E1%BB%A3i',
  None,
  'Chùa khởi công ngày 5/8/1956 và hoàn thành ngày 2/5/1958; tháp chuông cao 7 tầng được hoàn thành năm 1961.',
  'https://vi.wikipedia.org/wiki/Ch%C3%B9a_X%C3%A1_L%E1%BB%A3i',
  [{'title': 'Cuộc tấn công chùa (rạng sáng 21/8/1963)',
    'description': 'Ngay sau nửa đêm 21/8/1963, Lực lượng Đặc biệt dưới quyền đại tá Lê Quang Tung cùng cảnh sát chiến đấu tấn công chùa '
                   'theo kế hoạch của Ngô Đình Nhu trong cuộc khủng hoảng Phật giáo.',
    'source': 'https://en.wikipedia.org/wiki/X%C3%A1_L%E1%BB%A3i_Pagoda_raids',
    'verified': True},
   {'title': 'Trái tim Thích Quảng Đức',
    'description': 'Trong cuộc tấn công, lực lượng của ông Nhu đã lục soát bàn thờ chính và lấy đi quả tim còn nguyên của Thích Quảng Đức '
                   'được lưu giữ tại chùa.',
    'source': 'https://en.wikipedia.org/wiki/X%C3%A1_L%E1%BB%A3i_Pagoda',
    'verified': True},
   {'title': 'Học xá Đại học Vạn Hạnh (1964-1966)',
    'description': 'Chùa từng là nơi diễn ra các lớp học của Viện Đại học Vạn Hạnh trong giai đoạn 1964-1966.',
    'source': 'https://vi.wikipedia.org/wiki/Ch%C3%B9a_X%C3%A1_L%E1%BB%A3i',
    'verified': True}],
  [{'title': 'Tháp chuông 32 mét',
    'description': 'Tháp chuông 7 tầng cao 32 mét, hoàn thành năm 1961, chứa quả chuông đồng nặng 2 tấn mô phỏng chuông chùa Thiên Mụ '
                   '(Huế).',
    'source': 'https://vi.wikipedia.org/wiki/Ch%C3%B9a_X%C3%A1_L%E1%BB%A3i',
    'verified': True},
   {'title': 'Kiến trúc hai tầng',
    'description': 'Chùa gồm chính điện phía trên và giảng đường phía dưới, thiết kế theo lối mới; tác giả là các kiến trúc sư Trần Văn '
                   'Dương và Đỗ Bá Vinh.',
    'source': 'https://vi.wikipedia.org/wiki/Ch%C3%B9a_X%C3%A1_L%E1%BB%A3i',
    'verified': True}]),
 ('Đền thờ Tả quân Lê Văn Duyệt',
  ('place_of_worship',),
  10.8021,
  106.697,
  'historical',
  'Khu lăng mộ và đền thờ Tả quân Lê Văn Duyệt (1764-1832) cạnh chợ Bà Chiểu, nên dân gian quen gọi là Lăng Ông Bà Chiểu.',
  'https://vi.wikipedia.org/wiki/L%C4%83ng_L%C3%AA_V%C4%83n_Duy%E1%BB%87t',
  None,
  'Lăng được xây sau khi Lê Văn Duyệt mất năm 1832; dưới thời Minh Mạng mộ bị san bằng và dựng bia, đến năm 1841 vua Thiệu Trị cho dẹp bia '
  'và đắp lại mộ.',
  'https://vi.wikipedia.org/wiki/L%C4%83ng_L%C3%AA_V%C4%83n_Duy%E1%BB%87t',
  [{'title': 'Vua Thiệu Trị cho đắp lại mộ (1841)',
    'description': 'Năm 1841, vua Thiệu Trị cho dẹp bỏ trụ đá và đắp lại mộ Lê Văn Duyệt.',
    'source': 'https://vi.wikipedia.org/wiki/L%C4%83ng_L%C3%AA_V%C4%83n_Duy%E1%BB%87t',
    'verified': True},
   {'title': 'Xếp hạng di tích quốc gia (16/11/1988)',
    'description': 'Lăng được công nhận di tích lịch sử - văn hóa quốc gia ngày 16/11/1988.',
    'source': 'https://vi.wikipedia.org/wiki/L%C4%83ng_L%C3%AA_V%C4%83n_Duy%E1%BB%87t',
    'verified': True},
   {'title': 'Đại trùng tu 2007-2008',
    'description': 'Sau các lần xây lại vào năm 1937 và 1948-1949, công trình được trùng tu lớn trong giai đoạn 2007-2008.',
    'source': 'https://vi.wikipedia.org/wiki/L%C4%83ng_L%C3%AA_V%C4%83n_Duy%E1%BB%87t',
    'verified': True}],
  [{'title': 'Lễ hội Khai hạ - Cầu an',
    'description': 'Lễ hội được tổ chức vào ngày 7 âm lịch với nghi lễ và hát bội, và được công nhận là di sản văn hóa phi vật thể quốc '
                   'gia năm 2022.',
    'source': 'https://vi.wikipedia.org/wiki/L%C4%83ng_L%C3%AA_V%C4%83n_Duy%E1%BB%87t',
    'verified': True},
   {'title': 'Kiến trúc triều Nguyễn',
    'description': 'Khu lăng rộng khoảng 18.501 m², bố trí theo trục giữa với kiểu mái trùng thiềm điệp ốc, trang trí bằng gốm khảm và '
                   'chạm gỗ.',
    'source': 'https://vi.wikipedia.org/wiki/L%C4%83ng_L%C3%AA_V%C4%83n_Duy%E1%BB%87t',
    'verified': True},
   {'title': 'Hai ngôi mộ',
    'description': 'Trong khu lăng có hai ngôi mộ, của Lê Văn Duyệt và bà Đỗ Thị Phẫn.',
    'source': 'https://vi.wikipedia.org/wiki/L%C4%83ng_L%C3%AA_V%C4%83n_Duy%E1%BB%87t',
    'verified': True}]),
 ('Chợ Bình Tây',
  ('market',),
  10.75,
  106.6535,
  'architectural',
  'Chợ Bình Tây (còn gọi là Chợ Lớn mới) là ngôi chợ đầu mối bán sỉ lớn của khu Chợ Lớn, mang kiến trúc Á Đông kết hợp kỹ thuật phương '
  'Tây.',
  'https://vi.wikipedia.org/wiki/Ch%E1%BB%A3_B%C3%ACnh_T%C3%A2y',
  None,
  'Chợ do thương gia Quách Đàm (Thông Hiệp) bỏ tiền xây để thay chợ cũ, sau khi con rạch được lấp năm 1923.',
  'https://vi.wikipedia.org/wiki/Ch%E1%BB%A3_B%C3%ACnh_T%C3%A2y',
  [{'title': 'Lễ khánh thành (28-30/9/1928)',
    'description': 'Chợ mới được khánh thành trong ba ngày, từ 28 đến 30/9/1928.',
    'source': 'https://vi.wikipedia.org/wiki/Ch%E1%BB%A3_B%C3%ACnh_T%C3%A2y',
    'verified': True},
   {'title': 'Trùng tu lớn (2016-2018)',
    'description': 'Chợ được trùng tu từ cuối năm 2016 đến tháng 11/2018 với kinh phí khoảng 104 tỷ đồng, giữ lại các chi tiết gốc như '
                   'ngói và mái ngói.',
    'source': 'https://vi.wikipedia.org/wiki/Ch%E1%BB%A3_B%C3%ACnh_T%C3%A2y',
    'verified': True}],
  [{'title': 'Quy mô gian hàng',
    'description': 'Chợ có 1.446 sạp bố trí ở tầng trệt và tầng lầu.',
    'source': 'https://vi.wikipedia.org/wiki/Ch%E1%BB%A3_B%C3%ACnh_T%C3%A2y',
    'verified': True}]),
 ('Chợ Tân Định',
  ('market',),
  10.7899,
  106.6901,
  'architectural',
  'Chợ Tân Định ở đường Hai Bà Trưng (quận 1) là ngôi chợ kiến trúc Pháp với ba tháp chuông ở mặt tiền, vốn nổi tiếng là chợ hàng cao cấp '
  'và buôn bán vải.',
  'https://vi.wikipedia.org/wiki/Ch%E1%BB%A3_T%C3%A2n_%C4%90%E1%BB%8Bnh',
  None,
  'Chợ có tên cũ là chợ Phú Hòa từ thế kỷ 19; công trình hiện nay khởi công năm 1926 và khánh thành ngày 26/7/1927.',
  'https://vi.wikipedia.org/wiki/Ch%E1%BB%A3_T%C3%A2n_%C4%90%E1%BB%8Bnh',
  [{'title': 'Xây dựng và khánh thành (1926-1927)',
    'description': 'Chợ do công ty SIDEC của Pháp thiết kế và xây, tổn phí 110.000 đồng piastre, khánh thành ngày 26/7/1927 với sự tham dự '
                   'của Thống đốc Nam Kỳ.',
    'source': 'https://vi.wikipedia.org/wiki/Ch%E1%BB%A3_T%C3%A2n_%C4%90%E1%BB%8Bnh',
    'verified': True}],
  [{'title': 'Ba tháp chuông',
    'description': 'Mặt tiền chợ có ba tháp chuông, một tháp ở giữa và hai tháp hai bên.',
    'source': 'https://vi.wikipedia.org/wiki/Ch%E1%BB%A3_T%C3%A2n_%C4%90%E1%BB%8Bnh',
    'verified': True},
   {'title': 'Chợ cao cấp và trung tâm vải',
    'description': 'Chợ có tiếng là chợ cao cấp, giá cao, hàng tốt từ tỉnh Gia Định, đồng thời là nơi buôn bán vải sợi lớn.',
    'source': 'https://vi.wikipedia.org/wiki/Ch%E1%BB%A3_T%C3%A2n_%C4%90%E1%BB%8Bnh',
    'verified': True}]),
 ('Chợ Bà Chiểu',
  ('market',),
  10.8017,
  106.6988,
  'cultural',
  'Chợ Bà Chiểu là ngôi chợ trung tâm lâu đời của vùng Gia Định xưa, nay thuộc phường Gia Định, bán hơn 40 nhóm hàng như đồ gia dụng, quần '
  'áo, giày dép và nón.',
  'https://vi.wikipedia.org/wiki/Ch%E1%BB%A3_B%C3%A0_Chi%E1%BB%83u',
  None,
  'Chợ hình thành từ thế kỷ 19 như một nơi họp chợ nhỏ, từng có tên chợ Xổm; năm 1942 chợ được xây dựng chính thức dưới sự chủ trì của '
  'doanh nhân Trần Văn Chơi.',
  'https://vi.wikipedia.org/wiki/Ch%E1%BB%A3_B%C3%A0_Chi%E1%BB%83u',
  [{'title': 'Xây dựng chính thức (1942)',
    'description': 'Năm 1942, chợ được xây dựng chính thức do doanh nhân Trần Văn Chơi chủ trì.',
    'source': 'https://vi.wikipedia.org/wiki/Ch%E1%BB%A3_B%C3%A0_Chi%E1%BB%83u',
    'verified': True},
   {'title': 'Sửa chữa nâng cấp (1987)',
    'description': 'Chợ được sửa chữa, nâng cấp vào năm 1987.',
    'source': 'https://vi.wikipedia.org/wiki/Ch%E1%BB%A3_B%C3%A0_Chi%E1%BB%83u',
    'verified': True}],
  [{'title': 'Nguồn gốc tên gọi',
    'description': "Theo nhà văn Sơn Nam, tên Bà Chiểu có từ thời Tự Đức, trong đó 'chiểu' là vùng ao đầm tự nhiên, gắn với việc thờ một "
                   'vị bà gần nơi đó.',
    'source': 'https://vi.wikipedia.org/wiki/Ch%E1%BB%A3_B%C3%A0_Chi%E1%BB%83u',
    'verified': True},
   {'title': 'Quy mô',
    'description': 'Chợ rộng khoảng 8.465 m2, có khoảng 800 sạp, chia thành 8 khu chính.',
    'source': 'https://vi.wikipedia.org/wiki/Ch%E1%BB%A3_B%C3%A0_Chi%E1%BB%83u',
    'verified': True}]),
 ('Công viên Gia Định',
  ('park',),
  10.8125,
  106.6752,
  'nature',
  'Công viên Gia Định là không gian xanh đô thị rộng khoảng 5,8 ha ở khu vực Hạnh Thông, nơi người dân tập thể dục, vui chơi và là địa '
  'điểm tổ chức hội hoa xuân.',
  'https://vi.wikipedia.org/wiki/C%C3%B4ng_vi%C3%AAn_Gia_%C4%90%E1%BB%8Bnh',
  None,
  'Nơi này vốn là sân golf lập năm 1950, đến ngày 11/12/1978 được chính thức đặt tên là Công viên Gia Định theo quyết định của thành phố.',
  'https://vi.wikipedia.org/wiki/C%C3%B4ng_vi%C3%AAn_Gia_%C4%90%E1%BB%8Bnh',
  [{'title': 'Thành lập công viên (11/12/1978)',
    'description': 'Sân golf cũ được chuyển thành Công viên Gia Định theo quyết định của thành phố ngày 11/12/1978.',
    'source': 'https://vi.wikipedia.org/wiki/C%C3%B4ng_vi%C3%AAn_Gia_%C4%90%E1%BB%8Bnh',
    'verified': True},
   {'title': 'Khu vui chơi trẻ em (5/2012)',
    'description': 'Từ tháng 5/2012 công viên có khu vui chơi trẻ em rộng khoảng 8.300 m2, kinh phí trên 12 tỷ đồng.',
    'source': 'https://vi.wikipedia.org/wiki/C%C3%B4ng_vi%C3%AAn_Gia_%C4%90%E1%BB%8Bnh',
    'verified': True}],
  [{'title': 'Cây xanh',
    'description': 'Công viên có gần 700 cây thuộc nhiều loài; khoảng 59% diện tích là bãi cỏ.',
    'source': 'https://vi.wikipedia.org/wiki/C%C3%B4ng_vi%C3%AAn_Gia_%C4%90%E1%BB%8Bnh',
    'verified': True},
   {'title': 'Rạp xiếc',
    'description': 'Từ năm 2013 công viên là nơi đặt rạp xiếc của thành phố.',
    'source': 'https://vi.wikipedia.org/wiki/C%C3%B4ng_vi%C3%AAn_Gia_%C4%90%E1%BB%8Bnh',
    'verified': True}]),
 ('Công viên Văn hóa Đầm Sen',
  ('theme_park',),
  10.7643,
  106.6385,
  'cultural',
  'Công viên Văn hóa Đầm Sen rộng khoảng 50 ha trên đường Hòa Bình, có hơn 30 khu vui chơi, công viên nước, thủy cung và nhiều trò chơi '
  'cảm giác mạnh.',
  'https://vi.wikipedia.org/wiki/C%C3%B4ng_vi%C3%AAn_v%C4%83n_h%C3%B3a_%C4%90%E1%BA%A7m_Sen',
  None,
  'Trước 1975 đây là vùng đầm lầy bỏ hoang; giai đoạn 1976-1978 thành phố huy động hàng nghìn lao động xây dựng, và năm 1983 phần 30 ha '
  'đầu tiên mở cửa.',
  'https://vi.wikipedia.org/wiki/C%C3%B4ng_vi%C3%AAn_v%C4%83n_h%C3%B3a_%C4%90%E1%BA%A7m_Sen',
  [{'title': 'Mở cửa giai đoạn đầu (1983)',
    'description': 'Năm 1983, khu 30 ha đầu tiên của công viên được mở cửa đón khách.',
    'source': 'https://vi.wikipedia.org/wiki/C%C3%B4ng_vi%C3%AAn_v%C4%83n_h%C3%B3a_%C4%90%E1%BA%A7m_Sen',
    'verified': True},
   {'title': 'Chuyển giao quản lý (1989)',
    'description': 'Năm 1989, công viên được giao cho Công ty Dịch vụ Du lịch Phú Thọ quản lý.',
    'source': 'https://vi.wikipedia.org/wiki/C%C3%B4ng_vi%C3%AAn_v%C4%83n_h%C3%B3a_%C4%90%E1%BA%A7m_Sen',
    'verified': True}],
  [{'title': 'Thủy cung',
    'description': 'Thủy cung lập năm 1994, xây lại năm 2013, rộng hơn 3.000 m2 với cá mập, cá koi và các loài cá từ sông Mê Kông, rạn san '
                   'hô.',
    'source': 'https://vi.wikipedia.org/wiki/C%C3%B4ng_vi%C3%AAn_v%C4%83n_h%C3%B3a_%C4%90%E1%BA%A7m_Sen',
    'verified': True},
   {'title': 'Nhạc nước laser',
    'description': 'Nhà hát nhạc nước laser xây năm 2005 với kinh phí 12 tỷ đồng.',
    'source': 'https://vi.wikipedia.org/wiki/C%C3%B4ng_vi%C3%AAn_v%C4%83n_h%C3%B3a_%C4%90%E1%BA%A7m_Sen',
    'verified': True}]),
 ('Địa Đạo Bến Dược',
  ('museum',),
  11.1433,
  106.4632,
  'historical',
  'Địa đạo Bến Dược ở Củ Chi từng là căn cứ của Khu ủy và Bộ Tư lệnh Quân khu Sài Gòn - Chợ Lớn - Gia Định trong kháng chiến, nay là di '
  'tích quốc gia đặc biệt.',
  'https://www.sggp.org.vn/luu-dau-di-san-post583979.html',
  None,
  'Hệ thống địa đạo Củ Chi bắt đầu được đào từ năm 1948; đến năm 1965 đã hoàn thành khoảng 200 km.',
  'https://vi.wikipedia.org/wiki/%C4%90%E1%BB%8Ba_%C4%91%E1%BA%A1o_C%E1%BB%A7_Chi',
  [{'title': 'Xếp hạng Di tích quốc gia đặc biệt (2016)',
    'description': 'Năm 2016, địa đạo Bến Dược được xếp hạng Di tích quốc gia đặc biệt.',
    'source': 'https://www.sggp.org.vn/luu-dau-di-san-post583979.html',
    'verified': True}],
  [{'title': 'Đền tưởng niệm liệt sĩ',
    'description': 'Đền tưởng niệm tại đây ghi danh 44.520 liệt sĩ.',
    'source': 'https://www.sggp.org.vn/luu-dau-di-san-post583979.html',
    'verified': True},
   {'title': 'Cấu trúc nhiều tầng',
    'description': 'Địa đạo Củ Chi có ba tầng ở các độ sâu khác nhau, tầng trên cách mặt đất khoảng 3 m, tầng dưới sâu 8-12 m.',
    'source': 'https://vi.wikipedia.org/wiki/%C4%90%E1%BB%8Ba_%C4%91%E1%BA%A1o_C%E1%BB%A7_Chi',
    'verified': True}]),
 ('Hội quán Hà Chương',
  ('place_of_worship',),
  10.7532,
  106.658,
  'architectural',
  'Hội quán Hà Chương ở 802 Nguyễn Trãi là hội quán của người Hoa gốc Phúc Kiến, thờ chính Thiên Hậu Thánh mẫu và mang phong cách đền miếu '
  'Phúc Kiến.',
  'https://vi.wikipedia.org/wiki/H%E1%BB%99i_qu%C3%A1n_H%C3%A0_Ch%C6%B0%C6%A1ng',
  None,
  'Hội quán được xây dựng năm 1809 trên khuôn viên khoảng 2.400 m2, do cộng đồng người Hoa Phúc Kiến, đặc biệt là người từ Chương Châu và '
  'Tuyền Châu, lập nên.',
  'https://vi.wikipedia.org/wiki/H%E1%BB%99i_qu%C3%A1n_H%C3%A0_Ch%C6%B0%C6%A1ng',
  [{'title': 'Xếp hạng di tích quốc gia (28/12/2001)',
    'description': 'Hội quán được công nhận là di tích lịch sử - văn hóa quốc gia theo Quyết định 52/2001/QĐ-BVHTT ngày 28/12/2001.',
    'source': 'https://vi.wikipedia.org/wiki/H%E1%BB%99i_qu%C3%A1n_H%C3%A0_Ch%C6%B0%C6%A1ng',
    'verified': True}],
  [{'title': 'Chuông đồng thời Đồng Trị',
    'description': 'Hội quán còn giữ một quả chuông lớn khắc niên hiệu Đồng Trị, năm Mậu Thìn (1868).',
    'source': 'https://vi.wikipedia.org/wiki/H%E1%BB%99i_qu%C3%A1n_H%C3%A0_Ch%C6%B0%C6%A1ng',
    'verified': True},
   {'title': 'Cột đá chạm rồng',
    'description': 'Ban đầu có sáu cột đá nguyên khối chạm rồng, hiện còn bốn cột.',
    'source': 'https://vi.wikipedia.org/wiki/H%E1%BB%99i_qu%C3%A1n_H%C3%A0_Ch%C6%B0%C6%A1ng',
    'verified': True}]),
 ('Hội quán Tam Sơn',
  ('place_of_worship',),
  10.7525,
  106.6617,
  'cultural',
  'Hội quán Tam Sơn ở 118 Triệu Quang Phục là hội quán của người Hoa gốc Phúc Kiến, ban đầu thờ bà Kim Hoa và nay chủ yếu thờ Thiên Hậu.',
  'https://vi.wikipedia.org/wiki/H%E1%BB%99i_qu%C3%A1n_Tam_S%C6%A1n',
  None,
  'Không rõ năm xây ban đầu; ghi chép sớm nhất còn lại là lần sửa chữa hội quán năm 1796, và công trình tiếp tục được trùng tu nhiều lần '
  'vào các năm 1887, 1954, 1961, 1965, 1993.',
  'https://vi.wikipedia.org/wiki/H%E1%BB%99i_qu%C3%A1n_Tam_S%C6%A1n',
  [{'title': 'Công nhận di tích cấp thành phố (25/6/2015)',
    'description': 'Ngày 25/6/2015, UBND TP.HCM xếp hạng hội quán là di tích kiến trúc nghệ thuật cấp thành phố.',
    'source': 'https://vi.wikipedia.org/wiki/H%E1%BB%99i_qu%C3%A1n_Tam_S%C6%A1n',
    'verified': True}],
  [{'title': 'Thờ bà Kim Hoa',
    'description': "Hội quán ban đầu thờ bà Kim Hoa (bà mụ), có tấm biển năm 1834 ghi 'Sắc tứ Thánh mẫu điện'; về sau Thiên Hậu trở thành "
                   'vị thần chính.',
    'source': 'https://vi.wikipedia.org/wiki/H%E1%BB%99i_qu%C3%A1n_Tam_S%C6%A1n',
    'verified': True},
   {'title': 'Lễ hội',
    'description': 'Hội quán tổ chức lễ vía Thiên Hậu (23 tháng 3 âm lịch) và lễ cúng cô hồn (rằm tháng 10 âm lịch).',
    'source': 'https://vi.wikipedia.org/wiki/H%E1%BB%99i_qu%C3%A1n_Tam_S%C6%A1n',
    'verified': True}])]


_FIND_POI = sa.text(
    """
    SELECT p.id::text AS id, p.name
    FROM pois p
    WHERE p.category = ANY(CAST(:categories AS text[]))
      AND ST_DWithin(
          p.location,
          ST_SetSRID(ST_MakePoint(:lon, :lat), 4326)::geography,
          :radius_m
      )
      AND similarity(p.normalized_name, :normalized_name) >= :min_similarity
    ORDER BY
        similarity(p.normalized_name, :normalized_name) DESC,
        ST_Distance(p.location, ST_SetSRID(ST_MakePoint(:lon, :lat), 4326)::geography),
        p.id
    LIMIT 1
    """
)

_INSERT = sa.text(
    """
    INSERT INTO poi_knowledge (
        poi_id, content_type, intro, specialty, historical_context,
        historical_events, interesting_facts, source, verified
    )
    VALUES (
        CAST(:poi_id AS uuid), :content_type, :intro, :specialty,
        :historical_context, CAST(:historical_events AS jsonb),
        CAST(:interesting_facts AS jsonb), :source, true
    )
    ON CONFLICT (poi_id) DO NOTHING
    RETURNING poi_id
    """
)


def _normalize(value: str) -> str:
    """Cùng quy tắc với `app.poi_features.normalize_text`."""
    text = value.replace("Đ", "D").replace("đ", "d")
    decomposed = unicodedata.normalize("NFKD", text)
    ascii_text = "".join(char for char in decomposed if not unicodedata.combining(char))
    return re.sub(r"[^a-z0-9]+", " ", ascii_text.lower()).strip()


def _find(connection, name: str, categories: tuple[str, ...], lat: float, lon: float):
    return connection.execute(
        _FIND_POI,
        {
            "normalized_name": _normalize(name),
            "categories": list(categories),
            "lat": lat,
            "lon": lon,
            "radius_m": _RADIUS_M,
            "min_similarity": _MIN_SIMILARITY,
        },
    ).first()


def upgrade() -> None:
    connection = op.get_bind()
    for (name, categories, lat, lon, content_type, intro, intro_source, specialty,
         context, context_source, events, facts) in ROWS:
        match = _find(connection, name, categories, lat, lon)
        if match is None:
            logger.warning("poi_knowledge more_landmarks: KHÔNG tìm thấy POI cho %s", name)
            continue
        inserted = connection.execute(
            _INSERT,
            {
                "poi_id": match.id,
                "content_type": content_type,
                "intro": intro,
                "specialty": specialty,
                "historical_context": context,
                "historical_events": json.dumps(events, ensure_ascii=False),
                "interesting_facts": json.dumps(facts, ensure_ascii=False),
                "source": context_source or intro_source,
            },
        ).first()
        logger.info(
            "poi_knowledge more_landmarks: %s -> %s (%s)%s",
            name, match.id, match.name, "" if inserted else " — đã có kiến thức, bỏ qua",
        )


def downgrade() -> None:
    connection = op.get_bind()
    for name, categories, lat, lon, *_ in ROWS:
        match = _find(connection, name, categories, lat, lon)
        if match is not None:
            connection.execute(
                sa.text("DELETE FROM poi_knowledge WHERE poi_id = CAST(:poi_id AS uuid) AND verified"),
                {"poi_id": match.id},
            )
